-- MySQL Script generated by MySQL Workbench
-- Sun Feb  9 17:46:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bankApp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bankApp` ;

-- -----------------------------------------------------
-- Schema bankApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bankApp` DEFAULT CHARACTER SET utf8 ;
USE `bankApp` ;

-- -----------------------------------------------------
-- Table `bankApp`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankApp`.`manager` ;

CREATE TABLE IF NOT EXISTS `bankApp`.`manager` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(150) NULL,
  `last_name` VARCHAR(150) NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankApp`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankApp`.`client` ;

CREATE TABLE IF NOT EXISTS `bankApp`.`client` (
  `id` VARCHAR(45) NOT NULL,
  `status` INT NULL,
  `tax_code` VARCHAR(150) NULL,
  `first_name` VARCHAR(150) NULL,
  `last_name` VARCHAR(150) NULL,
  `email` VARCHAR(45) NULL,
  `address` VARCHAR(250) NULL,
  `phone` VARCHAR(45) NULL,
  `clientcol` VARCHAR(45) NULL,
  `manager_id` INT NOT NULL,
  PRIMARY KEY (`id`, `manager_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_client_manager1_idx` (`manager_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `bankApp`.`manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankApp`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankApp`.`account` ;

CREATE TABLE IF NOT EXISTS `bankApp`.`account` (
  `id` INT NOT NULL,
  `name` VARCHAR(150) NULL,
  `type` VARCHAR(15) NULL,
  `status` VARCHAR(15) NULL,
  `balance` DECIMAL(15,2) NULL,
  `currency_code` VARCHAR(3) NULL,
  `client_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `client_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_account_client_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `bankApp`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankApp`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankApp`.`product` ;

CREATE TABLE IF NOT EXISTS `bankApp`.`product` (
  `id` INT NOT NULL,
  `name` VARCHAR(150) NULL,
  `status` INT NULL,
  `currency_code` VARCHAR(5) NULL,
  `interest_rate` DECIMAL(3,2) NULL,
  `product_limit` DECIMAL(15,2) NULL,
  `manager_id` INT NOT NULL,
  PRIMARY KEY (`id`, `manager_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_product_manager1_idx` (`manager_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `bankApp`.`manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankApp`.`agreements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankApp`.`agreements` ;

CREATE TABLE IF NOT EXISTS `bankApp`.`agreements` (
  `id` INT NOT NULL,
  `interest_rate` DECIMAL(3,2) NULL,
  `status` INT NULL,
  `sum` DECIMAL(15,2) NULL,
  `account_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`, `account_id`, `product_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_agreements_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_agreements_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_agreements_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `bankApp`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agreements_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `bankApp`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankApp`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankApp`.`transaction` ;

CREATE TABLE IF NOT EXISTS `bankApp`.`transaction` (
  `id` INT NOT NULL,
  `type` INT NULL,
  `amount` DECIMAL(15,2) NULL,
  `desription` VARCHAR(150) NULL,
  `debit_account_id` INT NOT NULL,
  `credit_account_id` INT NOT NULL,
  PRIMARY KEY (`id`, `debit_account_id`, `credit_account_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_transaction_account1_idx` (`debit_account_id` ASC) VISIBLE,
  INDEX `fk_transaction_account2_idx` (`credit_account_id` ASC) VISIBLE,
  UNIQUE INDEX `credit_account_id_UNIQUE` (`credit_account_id` ASC) VISIBLE,
  UNIQUE INDEX `debit_account_id_UNIQUE` (`debit_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_account1`
    FOREIGN KEY (`debit_account_id`)
    REFERENCES `bankApp`.`account` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_account2`
    FOREIGN KEY (`credit_account_id`)
    REFERENCES `bankApp`.`account` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
